# Generated by Django 5.2.5 on 2025-09-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('materias', '0002_alter_materia_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(related_name='estudiantes', to='materias.materia'),
        ),
    ]
